drone:  
  model_name: "hummingbird"

sensor:
  lidar_range: 4.
  lidar_vfov: [-10, 20.] # degree
  lidar_vbeams: 4 # number of vertical beams
  lidar_hres: 10. # degree
  lidar_stack_T: 1 # number of frames to stack

  camera_width: 3.2
  camera_height: 2.4
  camera_fov: 90. # degree
  camera_resolution: 0.05 # meter per pixel
  camera_range: 5.
  